# Generated by Django 2.2.12 on 2021-07-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employeeSalary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeSalary', to='ems.Employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_employee', to='ems.Employee'),
        ),
    ]
