# Generated by Django 2.2.12 on 2021-07-07 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120, unique=True)),
                ('employee_email', models.EmailField(max_length=64, unique=True)),
                ('employee_phone', models.CharField(max_length=32, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Designation')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Team')),
            ],
        ),
    ]
