# Generated by Django 2.2.12 on 2021-07-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation_id',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='team_id',
            new_name='team',
        ),
    ]
