# Generated by Django 2.2.12 on 2021-07-08 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20210707_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_exit', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Employee')),
            ],
        ),
    ]
