# Generated by Django 2.2.12 on 2021-07-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='account_no',
            field=models.CharField(max_length=32),
        ),
    ]
